feat: investment update & delete in detail page
team5-ViewMyStartup/2-view-my-startup-5-BE pull request #14
Opened 2024-10-03 13:07 UTC by gahyeon-yang

### 🔎 작업 내용

investments 수정하기 삭제하기 코드 추가

### 🔧 앞으로의 과제

user 받아온 뒤 패스워드 처리하기

2024-10-03 13:42 UTC, ciin1411 approved these changes

2024-10-03 15:16 UTC, woonie-potato approved these changes

2024-10-03 15:16 UTC, ciin1411 commented on src/apis/investments.js
> +    const investment = await Investment.findById(investmentId);
이거는 uuid안쓰고 Objectid 쓰는건가요?

2024-10-03 15:18 UTC, ciin1411 reviewed
잘못 작성했습니다

2024-10-03 15:19 UTC, ciin1411 requested changes
uuid, objectid 통일하는게 좋을것 같아요

2024-10-05 04:43 UTC, gahyeon-yang commented on src/apis/investments.js
> +    const investment = await Investment.findById(investmentId);
지금 수정과 삭제 부분은 저번에 임의적으로 작성한 것이라서 오늘 수정할 예정입니다.

2024-10-05 17:22 UTC, MCprotein requested changes

2024-10-05 17:22 UTC, MCprotein commented on src/apis/investments.js
> +    await investment.save();
@gahyeon-yang 이렇게 저장하는 방식 말고 해당 아이디를 갖는 문서가 존재하는지 확인 후 findoneandupdate 메소드를 사용하시는게 좋아요
원자성을 지키게 업데이트가 되거든요

https://mongoosejs.com/docs/tutorials/findoneandupdate.html#how-to-use-code%3Efindoneandupdate()%3C/code%3E-in-mongoose

2024-10-05 17:22 UTC, MCprotein commented on src/apis/investments.js
> +    await investment.deleteOne();
@gahyeon-yang 여기도 findOneAndDelete 를 사용해서 원자적으로 업데이트 되도록 해주세요
https://mongoosejs.com/docs/api/model.html#Model.findOneAndDelete()

그리고 웬만하면 로직에 사용되는 데이터는 물리적으로 삭제하는게 아니라 논리적으로 삭제하는게 더 바람직합니다
hard delete와 soft delete에 대해 검색해보시고 변경해보세요

2024-10-05 17:22 UTC, MCprotein commented on src/apis/investments.js
> +    const { investorName, password } = req.body;
@gahyeon-yang 일반적으로 delete method에서는 request body를 사용하지 않습니다
오직 삭제만 행하기때문에 부수적인 데이터를 넘기지 않는게 좋아요

이 api에 대한 로직은 로그인을 구현할 경우, 현재 로그인된 사용자와 해당 투자의 투자자이름이 일치하는지만 보면 됩니다.
그래서 비밀번호 검증이 따로 필요없어요.
코드잇 요구사항에는 로그인이 없기때문에 비밀번호 입력칸이 있는거에요.
그래도 비밀번호 확인을 하고싶으면 header에 비밀번호를 암호화 해서 넣고 서버에서 검증하는 방법을 사용하세요

https://server0.tistory.com/entry/RESTful-API-DELETE-%EC%9A%94%EC%B2%AD%EC%97%90-Body%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EB%8A%94-%EC%9D%B4%EC%9C%A0

2024-10-08 09:08 UTC, ciin1411 approved these changes

2024-10-10 04:18 UTC, merged